create table transactions(
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  transaction varchar(255) not null,
  account varchar(255) not null,
  customer varchar(255) not null,
  value numeric(15,4) not null,
  type varchar(15) not null,
  primary key (id)
);

create table fraud(
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  hash_device varchar(255) not null,
  ip varchar(12) not null,
  transaction_id int8 not null,
  constraint fk_transactions foreign key (transaction_id) references transactions (id)
);

create sequence hibernate_sequence
